// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("rescript-ava/src/ava.cjs");
var Simple_sexp_parser = require("./simple_sexp_parser.cjs");

Ava.test("[Sexps] Char list to string", (function (t) {
        return Ava.is(t, Simple_sexp_parser.charListToString({
                        hd: /* 'h' */104,
                        tl: {
                          hd: /* 'e' */101,
                          tl: {
                            hd: /* 'l' */108,
                            tl: {
                              hd: /* 'l' */108,
                              tl: {
                                hd: /* 'o' */111,
                                tl: /* [] */0
                              }
                            }
                          }
                        }
                      }), "hello", undefined, undefined);
      }));

var P;

var Simple;

exports.P = P;
exports.Simple = Simple;
/*  Not a pure module */
