// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("rescript-ava/src/ava.cjs");
var Curry = require("rescript/lib/js/curry.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Res_parser = require("../src/res_parser.cjs");

function makeTests(parser, makeName, specs) {
  return Belt_Array.mapWithIndex(specs, (function (index, spec) {
                return [
                        parser,
                        Curry._2(makeName, index, spec),
                        spec
                      ];
              }));
}

function runTests(parser, makeName, specs) {
  var tests = makeTests(parser, makeName, specs);
  return Belt_Array.forEach(tests, (function (param) {
                var match = param[2];
                var remaining = match[2];
                var expected = match[1];
                var input = match[0];
                var parser = param[0];
                return Ava.test(param[1], (function (t) {
                              var err = Res_parser.run(parser, input);
                              if (err.TAG !== /* Ok */0) {
                                return Ava.fail(t, "Should not fail with \"" + err._0.message + "\"", undefined);
                              }
                              var match = err._0;
                              Ava.true_(t, Caml_obj.caml_equal(match[0], expected), undefined, undefined);
                              return Ava.true_(t, Res_parser.State.remaining(match[1]) === remaining, undefined, undefined);
                            }));
              }));
}

var P;

exports.P = P;
exports.makeTests = makeTests;
exports.runTests = runTests;
/* Ava Not a pure module */
