// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Parser = require("../src/parser.cjs");
var Lang_sexp_parser = require("./sexps/lang_sexp_parser.cjs");
var Lang_sexp_generator = require("./sexps/lang_sexp_generator.cjs");

var file = Fs.readFileSync("test.clj", "utf8");

var input = "(module test {" + file + "})";

var output = Parser.run(Lang_sexp_parser.parser, input);

var __x;

__x = output.TAG === /* Ok */0 ? Lang_sexp_generator.generate(output._0[0]) : output._0;

Fs.writeFileSync("test.clj.js", __x, "utf8");

exports.file = file;
exports.input = input;
exports.output = output;
/* file Not a pure module */
