// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("rescript-ava/src/ava.cjs");

Ava.skip("[JSON] valid true", (function (_t) {
        
      }));

var P;

exports.P = P;
/*  Not a pure module */
