// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Parser = require("../../src/parser.cjs");
var Json_helpers = require("./json_helpers.cjs");

function toString(t) {
  if (typeof t !== "number") {
    return "Number(" + t._0 + ")";
  }
  switch (t) {
    case /* Null */0 :
        return "Null";
    case /* True */1 :
        return "True";
    case /* False */2 :
        return "False";
    
  }
}

function _charToString(c) {
  return String.fromCharCode(c);
}

var $$null = Parser.map(Parser.string("null"), (function (param) {
        return /* Null */0;
      }));

var true_ = Parser.map(Parser.string("true"), (function (param) {
        return /* True */1;
      }));

var false_ = Parser.map(Parser.string("false"), (function (param) {
        return /* False */2;
      }));

var number = Parser.map(Json_helpers.number, (function (number) {
        return /* Number */{
                _0: number
              };
      }));

var P;

var Helpers;

exports.toString = toString;
exports.P = P;
exports.Helpers = Helpers;
exports._charToString = _charToString;
exports.$$null = $$null;
exports.true_ = true_;
exports.false_ = false_;
exports.number = number;
/* null Not a pure module */
