// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("rescript-ava/src/ava.cjs");
var Json = require("./parser/json.cjs");
var Res_parser = require("../../src/res_parser.cjs");

function run(param) {
  return Res_parser.run(Json.parse, param);
}

var tests = [
  [
    "\"1\"",
    "1"
  ],
  [
    "\"hello\"",
    "hello"
  ],
  [
    "\"   \"",
    "   "
  ],
  [
    "\"\"",
    ""
  ],
  [
    "\"\u0050\"",
    "P"
  ],
  [
    "\"\u0050\u0069\u0061n\u006F\"",
    "Piano"
  ]
];

Ava.skip("[JSON string]", (function (_t) {
        
      }));

var P;

exports.P = P;
exports.run = run;
exports.tests = tests;
/*  Not a pure module */
