// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("rescript-ava/src/ava.cjs");

Ava.skip("[JSON object]", (function (_t) {
        
      }));

/*  Not a pure module */
