// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("rescript-ava/src/ava.cjs");
var Json = require("./parser/json.cjs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Res_parser = require("../../src/res_parser.cjs");

function run(param) {
  return Res_parser.run(Json.parse, param);
}

var tests = [
  [
    "\"1\"",
    "1"
  ],
  [
    "\"hello\"",
    "hello"
  ],
  [
    "\"   \"",
    "   "
  ],
  [
    "\"\"",
    ""
  ],
  [
    "\"\u0050\"",
    "P"
  ],
  [
    "\"\u0050\u0069\u0061n\u006F\"",
    "Piano"
  ]
];

Belt_Array.forEach(tests, (function (param) {
        var expected = param[1];
        var input = param[0];
        return Ava.test("[JSON String] \"" + input + "\" succeeds", (function (t) {
                      var msg = Res_parser.run(Json.parse, input);
                      if (msg.TAG !== /* Ok */0) {
                        return Ava.fail(t, "Should not fail with \"" + msg._0 + "\"", undefined);
                      }
                      var match = msg._0;
                      var x = match[0];
                      if (typeof x !== "number" && x.TAG === /* String */2 && match[1] === "" && x._0 === expected) {
                        return Ava.pass(t, undefined, undefined);
                      }
                      return Ava.fail(t, "Should not succeed with \"" + Json.toString(x) + "\" and \"" + match[1] + "\" remaining", undefined);
                    }));
      }));

var P;

exports.P = P;
exports.run = run;
exports.tests = tests;
/*  Not a pure module */
