// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Parser = require("../../src/parser.cjs");

function toString(t) {
  switch (t) {
    case /* Null */0 :
        return "Null";
    case /* True */1 :
        return "True";
    case /* False */2 :
        return "False";
    
  }
}

var $$null = Parser.map(Parser.string("null"), (function (param) {
        return /* Null */0;
      }));

var P;

exports.toString = toString;
exports.P = P;
exports.$$null = $$null;
/* null Not a pure module */
