// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("rescript-ava/src/ava.cjs");
var Json = require("./parser/json.cjs");
var Res_parser = require("../../src/res_parser.cjs");

function run(param) {
  return Res_parser.run(Json.parse, param);
}

Ava.skip("[JSON Number]", (function (_t) {
        
      }));

var P;

var number = Json.number;

exports.P = P;
exports.number = number;
exports.run = run;
/*  Not a pure module */
