// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("rescript-ava/src/ava.cjs");
var Json = require("./parser/json.cjs");
var Res_parser = require("../../src/res_parser.cjs");

Ava.test("[JSON] valid true", (function (t) {
        var result = Res_parser.run(Json.parse, "true");
        if (result.TAG !== /* Ok */0) {
          return Ava.fail(t, "Parsing \"true\" returns an error of message: \"" + result._0 + "\"", undefined);
        }
        var match = result._0;
        var ast = match[0];
        if (ast !== 1) {
          return Ava.fail(t, "Parsing \"true\" returns an incorrect AST of " + Json.toString(ast), undefined);
        }
        var remaining = match[1];
        if (remaining === "") {
          return Ava.pass(t, undefined, undefined);
        } else {
          return Ava.fail(t, "Parsing \"true\" should return an empty string but got \"" + remaining + "\"", undefined);
        }
      }));

Ava.test("[JSON] invalid true", (function (t) {
        var result = Res_parser.run(Json.parse, "ttrue");
        if (result.TAG === /* Ok */0) {
          Ava.fail(t, undefined, undefined);
        } else {
          Ava.pass(t, "Parsing \"true_\" should return an error message", undefined);
        }
        var result$1 = Res_parser.run(Json.parse, "false");
        if (result$1.TAG === /* Ok */0) {
          if (result$1._0[0] === 1) {
            Ava.fail(t, undefined, undefined);
          } else {
            Ava.pass(t, "Parsing \"true_\" should return an error message", undefined);
          }
        } else {
          Ava.pass(t, "Parsing \"true_\" should return an error message", undefined);
        }
        var result$2 = Res_parser.run(Json.parse, "-true");
        if (result$2.TAG === /* Ok */0) {
          return Ava.fail(t, undefined, undefined);
        } else {
          return Ava.pass(t, "Parsing \"true_\" should return an error message", undefined);
        }
      }));

Ava.test("[JSON] valid false", (function (t) {
        var result = Res_parser.run(Json.parse, "false");
        if (result.TAG !== /* Ok */0) {
          return Ava.fail(t, "Parsing \"false\" returns an error of message: \"" + result._0 + "\"", undefined);
        }
        var match = result._0;
        var ast = match[0];
        if (typeof ast === "number" && ast >= 2) {
          var remaining = match[1];
          if (remaining === "") {
            return Ava.pass(t, undefined, undefined);
          } else {
            return Ava.fail(t, "Parsing \"false\" should return an empty string but got \"" + remaining + "\"", undefined);
          }
        }
        return Ava.fail(t, "Parsing \"false\" returns an incorrect AST of " + Json.toString(ast), undefined);
      }));

Ava.test("[JSON] invalid false", (function (t) {
        var result = Res_parser.run(Json.parse, "tfalse");
        if (result.TAG === /* Ok */0) {
          Ava.fail(t, undefined, undefined);
        } else {
          Ava.pass(t, "Parsing \"false_\" should return an error message", undefined);
        }
        var result$1 = Res_parser.run(Json.parse, "{false");
        if (result$1.TAG !== /* Ok */0) {
          return Ava.pass(t, "Parsing \"false_\" should return an error message", undefined);
        }
        return Ava.fail(t, undefined, undefined);
      }));

var P;

exports.P = P;
/*  Not a pure module */
