// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Parser = require("../../src/parser.cjs");
var Belt_List = require("rescript/lib/js/belt_List.js");

function toString(t) {
  if (typeof t !== "number") {
    return "Number(" + t._0 + ")";
  }
  switch (t) {
    case /* Null */0 :
        return "Null";
    case /* True */1 :
        return "True";
    case /* False */2 :
        return "False";
    
  }
}

function _charToString(c) {
  return String.fromCharCode(c);
}

var $$null = Parser.map(Parser.string("null"), (function (param) {
        return /* Null */0;
      }));

var true_ = Parser.map(Parser.string("true"), (function (param) {
        return /* True */1;
      }));

var false_ = Parser.map(Parser.string("false"), (function (param) {
        return /* False */2;
      }));

var digit = Parser.map(Parser.satisfy(function (c) {
          if (c >= /* '0' */48) {
            return /* '9' */57 >= c;
          } else {
            return false;
          }
        }), _charToString);

Parser.choice([
      digit,
      Parser.map(Parser.andThen(digit, Parser.many(digit)), (function (param) {
              return Belt_List.reduce(param[1], param[0], (function (prim0, prim1) {
                            return prim0.concat(prim1);
                          }));
            }))
    ]);

var sign = Parser.optional(Parser.anyOf([
          /* '+' */43,
          /* '-' */45
        ]));

Parser.andThen(Parser.$$char(/* 'E' */69), sign);

var P;

var number = "";

exports.toString = toString;
exports.P = P;
exports._charToString = _charToString;
exports.$$null = $$null;
exports.true_ = true_;
exports.false_ = false_;
exports.number = number;
/* null Not a pure module */
