// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("rescript-ava/src/ava.cjs");
var Json = require("./parser/json.cjs");
var Res_parser = require("../../src/res_parser.cjs");

function run(param) {
  return Res_parser.run(Json.parse, param);
}

function shouldNotPass(param) {
  return "Should not pass with \"" + param[1] + "\" remaining";
}

Ava.skip("[JSON] Array succeeds", (function (_t) {
        
      }));

var P;

var shouldNotFail = "Should not fail";

exports.P = P;
exports.run = run;
exports.shouldNotPass = shouldNotPass;
exports.shouldNotFail = shouldNotFail;
/*  Not a pure module */
